indent_style: tab
indent_size: 2
tabWidth: 2
semi: true
singleQuote: false
max_line_length: 90
bracketSpacing: true

plugins:
  - prettier-plugin-java

overrides:
  - files: "*.java"
    options:
      printWidth: 120
      tabWidth: 2
      trailingComma: none
      semi: true
  - files: "*.js"
    options:
      singleQuote: true
      indent_size: 2
  - files: "*.yml"
    options:
      indent_size: 2
  - files: "*.xml"
    options:
      semi: false
