version: "3.8"

x-logging: &local-logging
  driver: "local"
  options:
    max-size: "20m"
    max-file: "50"

services:
  astm-http-bridge:
    container_name: astm-http-bridge
    image: ctsteele/astm-http-bridge:latest
    pull_policy: always
    ports:
      - "8442:8443"
      - "12000:12001"
    volumes:
      - ./configuration.yml:/app/configuration.yml
    environment:
      LOGGING_LEVEL_ORG_ITECH: INFO
    logging: *local-logging
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 2m
