server:
  port: 8443
management:
  endpoint:
    health:
      show-details: always
#  ssl:
#    enabled: true
#    keyStoreType: ${server.ssl.keyStoreType}
#    key-store: ${server.ssl.keyStorePath}
#    key-store-password: ${server.ssl.keyStorePassword}

