server:
  port: 8443
#  ssl:
#    enabled: true
#    keyStoreType: PKCS12
#    key-store: /path/to/keystore.p12
#    key-store-password: password
  http:
    port: 8080
    
management:
  endpoints:
    web:
      exposure:
        include: loggers
    loggers:
      enabled: true
